/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "./common";

export interface MoodInterface extends utils.Interface {
  functions: {
    "setMood(string)": FunctionFragment;
    "getMood()": FunctionFragment;
  };

  getFunction(nameOrSignatureOrTopic: "setMood" | "getMood"): FunctionFragment;

  encodeFunctionData(
    functionFragment: "setMood",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(functionFragment: "getMood", values?: undefined): string;

  decodeFunctionResult(functionFragment: "setMood", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getMood", data: BytesLike): Result;

  events: {};
}

export interface Mood extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: MoodInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    setMood(
      _mood: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    getMood(overrides?: CallOverrides): Promise<[string]>;
  };

  setMood(
    _mood: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  getMood(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    setMood(
      _mood: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    getMood(overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    setMood(
      _mood: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    getMood(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    setMood(
      _mood: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    getMood(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
