/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type { Mood, MoodInterface } from "../Mood";

const _abi = [
  {
    inputs: [
      {
        internalType: "string",
        name: "_mood",
        type: "string",
      },
    ],
    name: "setMood",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "getMood",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class Mood__factory {
  static readonly abi = _abi;
  static createInterface(): MoodInterface {
    return new utils.Interface(_abi) as MoodInterface;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): Mood {
    return new Contract(address, _abi, signerOrProvider) as Mood;
  }
}
